### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by damsdev1** [AlpacaFur/Artemis.CSGO#1]
The plugin doesn't hook to csgo anymore

**Comment by AlpacaFur** [comment]
Hi, sorry that it isn't working for you. Did you put the gamestate_integration_artemis.cfg file inside your CS:GO cfg folder (typically located "C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\cfg")?

**Comment by ghost** [comment]
Hi, excuse me I didn't read the README correctly, it works fine, 
Thanks.
