### ISSUE TITLE
Doesn't work on Artemis 2 (June 24, 2023)

### ISSUE THREAD

**Issue by gianluccaq** [AlpacaFur/Artemis.CSGO#4]
Hello! I just installed Artemis 2 and OpenRGB for my Hyperx Alloy Origins Core keyboard, and the pre-installed modules work perfectly, but this CSGO one doesn't. When I try to import the ZIP I get this message
"Please ensure the selected ZIP file is a valid Artemis plugin. Could not find a plugin.json in D:etc\etc\Artemis.CSGO.zip"

Please answer, I really want to try this with the game!
thx.

**Comment by AlpacaFur** [comment]
Hi, this repo was created a while ago and I haven't had time to bring it up to date with the latest Artemis updates. 

There's a newer version of this plugin that a team member made in the [Artemis.Plugins.Games](https://github.com/Artemis-RGB/Artemis.Plugins.Games) repo though, and that version is up to date!
